export * from './hero/Hero'
export * from './simpleText/SimpleText'
export * from './fullscreenMedia/FullscreenMedia'
export * from './faq/Faq'
export * from './storytelling/Storytelling'
export * from './carte/Carte'
export * from './contact/Contact'